Table messenger.messages {
  id int
  created_at datetime
  updated_at datetime
  sender_id int
  chat_id int
  text text
  pinned bool
}

Table messenger.messages_forward {
  parent_id int
  child_id int
}

Table messenger.chats {
  id int
  created_at datetime
  title varchar
  description text
  company_id int
  is_public bool
  is_closed bool
  pinned bool
}

Table messenger.users {
  id int
  created_at datetime
  last_visited datetime
  name varchar
  login varchar
  password hash
  role Enum
  company_id int
}

Table messenger.chats_users {
  chat_id int
  user_id int
  is_owner bool
  is_admin bool
}

Enum messenger.attachment_type {
  file
  image
  voice
}

Table messenger.attachments {
  id int
  created_at datetime
  url varchar
  thumb_url varchar
  size int
  type messenger.attachment_type
  duration int [null]
}

Table messenger.users_messages_read {
  user_id int
  message_id int
}

Table messenger.companies {
  id int
  name varchar
}

Table messenger.chat_events {
  id int
  created_at datetime
  type varchar
  message_id int
  payload json
}

Table messenger.conference {
  id int
  chat_id int
  start_time datetime
  call_url varchar
}


Ref: "messenger"."chats"."id" < "messenger"."messages"."chat_id"

Ref: "messenger"."chats"."id" < "messenger"."chats_users"."chat_id"

Ref: "messenger"."chats_users"."user_id" < "messenger"."users"."id"

Ref: "messenger"."attachments"."id" <> "messenger"."messages"."id"

Ref: "messenger"."users_messages_read"."user_id" < "messenger"."users"."id"

Ref: "messenger"."users_messages_read"."message_id" < "messenger"."messages"."id"

Ref: "messenger"."companies"."id" < "messenger"."chats"."company_id"

Ref: "messenger"."companies"."id" <> "messenger"."users"."company_id"

Ref: "messenger"."users"."id" < "messenger"."messages"."sender_id"

Ref: "messenger"."messages"."id" < "messenger"."messages_forward"."parent_id"
Ref: "messenger"."messages_forward"."child_id" > "messenger"."messages"."id"

Ref: "messenger"."messages"."id" < "messenger"."chat_events"."message_id"

Ref: "messenger"."chats"."id" <> "messenger"."conference"."chat_id"