openapi: 3.0.0
info:
  title: Corp Messenger API
  version: 1.0.0
  description: Retrieve and send messages
servers:
  - url: "http://messenger.rostkov.me/api"
    description: Продуктовый сервер
paths:
  /auth/register/:
    post:
      requestBody:
        description: Данные для регистрации нового пользователя
        content:
          application/json:
            schema:
              type: object
              required:
                - login
                - password
                - first_name
                - middle_name
                - last_name
              properties:
                login:
                  type: string
                  description: Имя пользователя
                password:
                  type: string
                  description: Пароль
                first_name:
                  type: string
                  description: Имя
                middle_name:
                  type: string
                  description: Отчество
                last_name:
                  type: string
                  description: Фамилия
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
          description: Пользователь успешно зарегистрирован
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Некорректные данные
        "409":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Пользователь с таким username уже существует
      operationId: registerUser
      tags:
        - auth
      summary: Регистрация нового пользователя
      description: Регистрация нового пользователя в системе
  /auth/login/:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCredentials"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tokens"
          description: Авторизация прошла успешно
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Неверный логин или пароль
      operationId: loginUser
      tags:
        - auth
      summary: Авторизация
      description: Авторизация пользователя в системе и получение токена
  /auth/renew/:
    post:
      parameters:
        - name: refreshToken
          description: Токен обновления
          schema:
            type: string
          in: query
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tokens"
          description: Токен обновлен
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Неверный токен обновления
      operationId: renewToken
      tags:
        - auth
      summary: Обновление токена
      description: Обновление токена доступа
  /chats/:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chats"
          description: Список чатов
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Неверный токен доступа
      operationId: getChats
      tags:
          - chats
      summary: Получение списка чатов
      description: Получение списка чатов пользователя
    post:
      requestBody:
        description: Данные для создания нового чата
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Chat"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chat"
          description: Чат успешно создан
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Некорректные данные
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Неверный токен доступа
      operationId: createChat
      tags:
        - chats
      summary: Создание нового чата
      description: Создание нового чата
  "/chats/{chatId}/":
    get:
      parameters:
        - name: chatId
          description: Идентификатор чата
          schema:
            type: integer
          in: path
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChatInstance"
          description: Информация о чате
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Неверный токен доступа
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Чат не найден
      operationId: getChat
      tags:
          - chats
      summary: Получение информации о чате
      description: Получение информации о чате
    put:
      requestBody:
        description: Данные для обновления информации о чате
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChatInstance"
        required: true
      parameters:
        - name: chatId
          description: Идентификатор чата
          schema:
            type: integer
          in: path
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chat"
          description: Информация о чате успешно обновлена
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Некорректные данные
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Неверный токен доступа
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Чат не найден
      operationId: updateChat
      tags:
          - chats
      summary: Обновление информации о чате
      description: Обновление информации о чате
    delete:
      parameters:
        - name: chatId
          description: Идентификатор чата
          schema:
            type: integer
          in: path
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chat"
          description: Чат успешно удален
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Неверный токен доступа
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Чат не найден
      operationId: deleteChat
      tags:
          - chats
      summary: Удаление чата
      description: Удаление чата
components:
  schemas:
    Tokens:
      type: object
      properties:
        accessToken:
          description: Токен доступа
          type: string
        refreshToken:
          description: Токен обновления
          type: string
    User:
      required:
        - username
        - password
      type: object
      properties:
        id:
          format: int64
          type: integer
        username:
          type: string
        password:
          format: password
          type: string
        company_id:
          format: string
          description: "ID компании, к которой принадлежит пользователь (шестнадцатеричный UUID)"
          type: integer
    Chat:
      description: Краткая информация о чате
      required:
        - name
      type: object
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        company_id:
          format: string
          description: "ID компании, к которой принадлежит чат (шестнадцатеричный UUID)"
          type: integer
    Chats:
      description: Список чатов
      type: array
      items:
        $ref: "#/components/schemas/Chat"
    ChatInstance:
      description: "Полная информация о чате, включая список участников"
      required:
        - name
      type: object
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        company_id:
          format: string
          description: "ID компании, к которой принадлежит чат (шестнадцатеричный UUID)"
          type: integer
        users:
          type: array
          items:
            $ref: "#/components/schemas/User"
    Error:
      required:
        - message
      type: object
      properties:
        message:
          description: A human readable error message
          type: string
    UserCredentials:
      description: Данные для авторизации пользователя
      required:
        - login
        - password
      type: object
      properties:
        login:
          description: Имя пользователя
          type: string
        password:
          description: Пароль пользователя
          type: string
  securitySchemes:
    AccessToken:
      type: apiKey
      name: AccessToken
      in: header
security:
  - AccessToken: [ ]
